server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xingfengsuiyu/springcloud-learn-parent.git
          searchPath: config/config
          username: xingfengsuiyu
          password: zc8737875.
      label: master
eureka:
  instance:
    hostname: localhost
#    hostname: ${spring.cloud.client.ipAddress}
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/