#server:
#  port: 8761
#
#eureka:
#  server:
#    enable-self-preservation: false
#  instance:
##    preferIpAddress: true
#    hostname: localhost
##    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/